dataset_path: /ML-A100/team/mm/zk/lmms-eval/vlms-bench-data-jsonl/infovqa/
task: "infovqa_suit_val"
test_split: train
output_type: generate_until
metric_list:
  - metric: anls
    aggregation: mean
    higher_is_better: true
include: _default_template_infovqa_yaml