dataset_path: Otter-AI/ScienceQA
task: "scienceqa"
test_split: test
output_type: generate_until
doc_to_visual: !function utils.sqa_doc_to_visual
doc_to_text: !function utils.sqa_doc_to_text
doc_to_target: !function utils.sqa_doc_to_target
generation_kwargs:
  until:
    - "ASSISTANT:"
metric_list:
  - metric: exact_match
    aggregation: mean
    higher_is_better: true
    ignore_case: true
    ignore_punctuation: true
metadata:
  - version: 0.0
