<<<<<<< HEAD
dataset_path: ./vlms-bench-data-VD/textvqa/
=======
dataset_path: /ML-A100/team/mm/zk/lmms-eval/vlms-bench-data-VD/textvqa/
>>>>>>> 865c7069caf994108f2fb1c2648cb346c8741a4e
task: textvqa_val_vd
test_split: train
metric_list:
  - metric: exact_match
    aggregation: mean
    higher_is_better: true
    ignore_case: true
    ignore_punctuation: true
  - metric: submission
    aggregation: !function utils.textvqa_aggregate_submissions
    higher_is_better: true
include: _default_template_textvqa_yaml
