task: "mmaadbench_base"
test_split: test
include: _default_template_mmaadbench_base_yaml
metric_list:
  - metric: gpt_eval_score
    aggregation: !function utils.mmaadbench_base
    higher_is_better: true