task: "mmivqdbench_option"
test_split: test
include: _default_template_mmivqdbench_option_yaml
metric_list:
  - metric: gpt_eval_score
    aggregation: !function utils.mmivqdbench_option
    higher_is_better: true