dataset_name: "multi-choice"
task: "tempcompass-multi-choice"
test_split: test
output_type: generate_until
doc_to_visual: !function utils.tempcompass_doc_to_visual
doc_to_text: !function utils.tempcompass_doc_to_text_multi_choice
doc_to_target: !function utils.tempcompass_doc_to_answer
process_results: !function utils.tempcompass_process_results_multi_choice
metric_list:
  - metric: accuracy
    aggregation: !function utils.tempcompass_aggregate_multi_choice
    higher_is_better: true
include: _default_template_yaml
