dataset_path: lmms-lab/RealWorldQA
dataset_kwargs:
  token: True
task: "realworldqa"
test_split: test
output_type: generate_until
doc_to_visual: !function utils.realworldqa_doc_to_visual
doc_to_text: !function utils.realworldqa_doc_to_text
doc_to_target: "answer"
generation_kwargs:
  max_new_tokens: 16
  temperature: 0
  top_p: 0
  num_beams: 1
  do_sample: false
metric_list:
  - metric: exact_match
    aggregation: mean
    higher_is_better: true
model_specific_prompt_kwargs:
  default:
    pre_prompt: ""
    post_prompt: "\nAnswer the question using a single word or phrase."
metadata:
  - version: 0.0
